Adding the "substitute" option.

diff --git a/artifact/bin/acc b/artifact/bin/acc
--- a/artifact/bin/acc
+++ b/artifact/bin/acc
@@ -38,6 +38,8 @@ function usage {
   echo "         --target-complexity   : Target simplified complexity (default: one less than"
   echo "                                 the input program's complexity)"
   echo "         --try-splitting       : Consider splits during simplification (default: false)"
+  echo "    -u,  --substitute          : A comma-delimited list of variables which will have all"
+  echo "                                 occurences substituted by its definition."
   echo "    -v,  --verbose             : Emit debug information during simplification exploration"
   echo "arguments:"
   echo "    ALPHA_FILE                 : Input Alpha file used to generate main ystem, makefile,"
@@ -167,6 +169,14 @@ while (( "$#" )); do
         exit 1
       fi
       ;;
+    -u|--substitute)
+      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+        substitute=$2
+        shift 2
+      else
+        echo "argument missing for -- $1" >&2
+      fi
+      ;;
     -*|--*=) # unsupported flags
       echo "unrecognized option -- $(echo $1 | sed 's~^-*~~')" >&2
       usage;
@@ -234,7 +244,8 @@ if [[ -n "$gen_new_writeC" ]]; then
          ACC_TARGET_COMPLEXITY=$target_complexity \
          ACC_TRY_SPLITTING=$try_splitting \
          ACC_VERBOSE=$verbose \
-         ACC_BASE_DATATYPE=$data_type
+         ACC_BASE_DATATYPE=$data_type \
+         ACC_SUBSTITUTE=$substitute
   java -jar ${BASE_DIR}/alpha.glue.v2.jar
   statuz="$?"
   if [[ -z "$simplify" ]]; then
